### ISSUE TITLE
RuntimeError when using CUDA

### ISSUE THREAD

**Issue by jwr1995** [inspiros/tvdcn#2]
I get the following error message only when trying to use CUDA
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
See example script below :-
```
>>> import tvdcn
>>> tvdcn.has_ops()
True
>>> tvdcn.with_cuda()
True
>>> from tvdcn.ops import DeformConv1d
>>> layer=DeformConv1d(3,3,3,device='cuda')
>>> import torch
>>> x=torch.randn(3,3,3).cuda()
>>> o=torch.randn(3,3,1).cuda()
>>> y=layer(x,o)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/tvdcn/ops/deform_conv.py", line 374, in forward
    return self._conv_forward(input, self.weight, offset, mask, self.bias)
  File "/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/tvdcn/ops/deform_conv.py", line 438, in _conv_forward
    return deform_conv1d(input, weight, offset, mask, bias,
  File "/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/tvdcn/ops/deform_conv.py", line 112, in deform_conv1d
    return torch.ops.tvdcn.deform_conv1d(
  File "/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Using the latest torch (2.0.1 not 2.0.0) with cuda 11.8 as this seems to be the only configuration that will install correctly using the pypi package.

**Comment by inspiros** [comment]
Hi, thanks for reporting, this error arises when Cuda code was not compiled to target your GPU architecture.

And yes the **PyPI** wheels are currently limited, I only uploaded the wheels for GPU with compute capability of `6.1`, `7.5`, `8.6`, and `8.9+PTX` (check this [link](https://developer.nvidia.com/cuda-gpus)). While they were compiled with the latest version of `torch` (which turned out to be `torch==2.0.1` not `torch==2.0.0` when I launched the GitHub Action) and Cuda 11.8, I believe they will run on any Cuda with major version 11.

I tested your code on a private Ubuntu machine with `torch==1.9.0+cu111` + `tvdcn==0.2.4` installed from PyPI, and it works:
```console
inspiros@oppenheimer:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
inspiros@oppenheimer:~$
inspiros@oppenheimer:~$ python
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.9.0+cu111'
>>> import tvdcn
>>> tvdcn.__version__
'0.2.4'
>>> from tvdcn.ops import DeformConv1d
>>> layer = DeformConv1d(3, 3, 3, device='cuda')
>>> x = torch.randn(3, 3, 3, device='cuda')
>>> o = torch.randn(3, 3, 1, device='cuda')
>>> y = layer(x, o)
>>> print(y.shape)
torch.Size([3, 3, 1])
```
Also, I will update the requirements to `torch>=1.9.0`, it is the lowest version that I can compile the extension.
You can rebuild the wheel on your machine if nothing works.
```
python setup.py bdist_wheel
pip install dist/*.whl
```

**Comment by jwr1995** [comment]
Thanks - I am using a V100 which is compute capability 7.0, I assume this is why I can't use wheels.

When I try to use `pip install .` I get a lot of error messages. I'm now using nvcc 11.5 and torch 1.12.1+cu113. I think maybe this is a c compiler issue but I have no clue. I am using gcc/++ 11.3. See error logs below

[logs.txt](https://github.com/inspiros/tvdcn/files/11496453/logs.txt)

[Update 12:01] I figured out this was a compatibility mismatch between nvcc 11.5, gcc 11.3 and cuda 11.3. I think this is now fixed by updating nvcc to 11.8. However there is now a linking issue for the cuda runtime library when using `pip install .` :
```
x86_64-conda_cos6-linux-gnu-c++ -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/acp19jwr/.conda/envs/speechbrain/lib -L/home/acp19jwr/.conda/envs/speechbrain/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/acp19jwr/.conda/envs/speechbrain/lib -L/home/acp19jwr/.conda/envs/speechbrain/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/acp19jwr/.conda/envs/speechbrain/lib -Wl,-rpath-link,/home/acp19jwr/.conda/envs/speechbrain/lib -L/home/acp19jwr/.conda/envs/speechbrain/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/acp19jwr/.conda/envs/speechbrain/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/acp19jwr/.conda/envs/speechbrain/include build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cpu/deform_conv1d_kernels_cpu.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cpu/deform_conv2d_kernels_cpu.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cpu/deform_conv3d_kernels_cpu.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cuda/deform_conv1d_kernels_cuda.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cuda/deform_conv2d_kernels_cuda.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/cuda/deform_conv3d_kernels_cuda.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv1d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv2d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv3d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv_transpose1d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv_transpose2d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/deform_conv_transpose3d.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/dispatch/deform_conv1d_kernels.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/dispatch/deform_conv2d_kernels.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/ops/dispatch/deform_conv3d_kernels.o build/temp.linux-x86_64-cpython-38/tvdcn/csrc/tvdcn.o -L/home/acp19jwr/.conda/envs/speechbrain/lib/python3.8/site-packages/torch/lib -L/home/acp19jwr/.conda/envs/speechbrain/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/tvdcn/_C.cpython-38-x86_64-linux-gnu.so
/home/acp19jwr/.conda/envs/speechbrain/bin/../lib/gcc/x86_64-conda-linux-gnu/11.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status
error: command '/home/acp19jwr/.conda/envs/speechbrain/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit code 1
```
This might be a problem from my side. Investigating further

**Comment by jwr1995** [comment]
@inspiros could you confirm what C compiler and version you are using? I have just tried compiling from source on an A100 and while it compiles seemingly fine, I still get `has_ops()` outputting `False` resulting in runtime errors.

**Comment by inspiros** [comment]
The compiler is decided by `setuptools`, usually it is `x86_64-linux-gnu-gcc`. This is the version on GitHub Action servers:
```console
$ x86_64-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=x8[6](https://github.com/inspiros/tvdcn/actions/runs/5005184499/jobs/8968778832#step:3:7)_64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x[8](https://github.com/inspiros/tvdcn/actions/runs/5005184499/jobs/8968778832#step:3:9)6_64-linux-gnu/[11](https://github.com/inspiros/tvdcn/actions/runs/5005184499/jobs/8968778832#step:3:12)/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
```
Building from source is pain, if `has_ops()` returns `False` it means the built binary can't be loaded for some reason.
I uploaded a new version `v0.2.5` which now supports both cc `7.0` (V100) and `8.0` (A100) (but you need to wait ~45 minutes from the time I post this for the GitHub Action to rebuild 😂). I hope the new **PyPI** wheel works on your device.

**Comment by jwr1995** [comment]
Neither of the wheels worked for me unfortunately, there must be something I am missing in terms of my environment. I can now compile everything in my V100 environment, this was an environment issue before, but I am still getting `has_ops==False` for every install method. Compiling from source is now working for the A100 so I can probably work with this if you want to close this issue.
